CREATE TABLE usuario (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE config (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tema BOOLEAN NOT NULL DEFAULT FALSE,
    idioma ENUM('portugues', 'ingles', 'espanhol') NOT NULL DEFAULT 'portugues',
    moeda ENUM('real', 'dolar', 'euro') NOT NULL DEFAULT 'real',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_id INT NOT NULL UNIQUE REFERENCES usuario(id) ON DELETE CASCADE,
);

CREATE TABLE categoria_despesa (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    cor VARCHAR(7) NOT NULL DEFAULT '#898989',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_id INT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
);

CREATE TABLE fonte_receita (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    cor VARCHAR(7) NOT NULL DEFAULT '#898989',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_id INT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
);

CREATE TABLE despesa (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    valor DECIMAL(11,2) NOT NULL CHECK (valor > 0),
    recorrente BOOLEAN NOT NULL DEFAULT FALSE,
    data DATE NOT NULL,
    data_vencimento DATE DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    categoria_despesa_id INT REFERENCES categoria_despesa(id),
    usuario_id INT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
);

CREATE TABLE receita (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    valor DECIMAL(11,2) NOT NULL CHECK (valor > 0),
    recorrente BOOLEAN NOT NULL DEFAULT FALSE,
    data DATE NOT NULL,
    data_vencimento DATE DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fonte_receita_id INT REFERENCES fonte_receita(id),
    usuario_id INT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
);

CREATE TABLE meta ( --budget
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(70) NOT NULL,
    valor DECIMAL(11,2) NOT NULL CHECK (valor > 0),
    economia_mensal DECIMAL(11,2) NOT NULL DEFAULT 0 CHECK (economia_mensal >= 0),
    data_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_id INT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
);